name: discord-push

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone project
      uses: actions/checkout@v2

    - name: Push commit message to discord
      uses: Mist3r-Robot/classic-discord-webhook@main
      with:
        id: ${{ secrets.DISCORD_WEBHOOK_ID_PRIVATE }}
        token: ${{ secrets.DISCORD_WEBHOOK_TOKEN_PRIVATE }}
