name: Pre-release

on:
  push:
    tags:
      - '**-alpha**'
      - '**-beta**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Package and release
        uses: BigWigsMods/packager@master

      - name: Upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: FreeUI
          path: .release/
