name: Package and build alpha/beta versions

on:
  push:
    tags:
      - '**alpha**'
      - '**beta**'


jobs:

  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: release.sh -w 0

      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
        if: always()
