name: pre-release

on:
  push:
    tags:
      - '*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Replace toc version
        uses: Numynum/ToCVersions@master

      - name: Package and release
        uses: BigWigsMods/packager@master

      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
        if: failure()
