name: pre-release

on:
  push:
    tags:
      - '*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.ref }}

      - name: Replace toc version
        uses: Numynum/ToCVersions@master

      - name: Package and release
        uses: BigWigsMods/packager@master

      - name: failure notification
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: error
            username: Rick Bot
            avatarUrl: https://cdn.discordapp.com/attachments/751929844920614932/934170534755860560/rick.png
            description: 'FAILURE'
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL_PRIVATE }}
        if: failure()

      - name: Release notification
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: warn
            username: Rick Bot
            avatarUrl: https://cdn.discordapp.com/attachments/751929844920614932/934170534755860560/rick.png
            text: '@here update available'
            description: '${{ github.event.repository.name }} ${{ github.ref_name }} has been released.'
            details: 'Please note that this is a BETA version and can only be downloaded from Github. https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/download/${{ github.ref_name }}/${{ github.event.repository.name }}-${{ github.ref_name }}.zip'
            footer: '⚡ Beta Release'
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}


