name: release

on:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.ref }}

      - name: Replace toc version
        uses: Numynum/ToCVersions@master

      - name: Package and release
        uses: BigWigsMods/packager@v2

      - name: failure notification
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: error
            username: Rick Bot
            avatarUrl: https://cdn.discordapp.com/attachments/751929844920614932/934170534755860560/rick.png
            description: 'FAILURE'
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL_PRIVATE }}
        if: failure()

      - name: Release notification
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            username: Morty Bot
            avatarUrl: https://cdn.discordapp.com/attachments/751929844920614932/934170534458056804/morty.png
            text: '@here update available'
            description: '${{ github.event.repository.name }} ${{ github.ref_name }} has been released.'
            details: 'Please note that this is a STABLE version and it is recommended to update it as soon as possible.'
            footer: '⭐ Stable Release'
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
