name: release

on:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.ref }}

      - name: Replace toc version
        uses: Numynum/ToCVersions@master

      - name: Package and release
        uses: BigWigsMods/packager@master

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '@here {{ EVENT_PAYLOAD.repository.name }} {{ GITHUB_REF_NAME }} has been released.'

      - name: Failure notification
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL_PRIVATE }}
          status: ${{ job.status }}
        if: failure()
