name: Package and build release versions

on:
  push:
    tags-ignore:
      - "**-alpha-**"
      - "**-beta-**"


jobs:

  build:

    runs-on: ubuntu-latest

    env:
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: release.sh -w 23258

      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
        if: always()
